//----------------------------------------------------------------------------
#ifndef CoptH
#define CoptH
//----------------------------------------------------------------------------
#define FT_STR_DEF_TITLE                "FTDI Serializer"
#define FT_STR_DEF_MANUFACTURER         "FTDI"
#define FT_STR_DEF_MANUFACTURER_ID      "FT"
#define FT_INT_DEF_VENDOR_ID            0x0403
#define FT_INT_DEF_PRODUCT_ID           0x6001
#define FT_STR_DEF_PRODUCT_DESC         "USB Serial Converter"
#define FT_INT_DEF_MAX_POWER            44
#define FT_STR_DEF_FIXED_SERNO          "00000000"
#define FT_STR_DEF_USB_VERSION          "0110"
#define FT_INT_DEF_PNP                  1
#define FT_INT_DEF_SELF_POWERED         0
#define FT_INT_DEF_REMOTE_WAKEUP        1
#define FT_BOOL_DEF_BM                  true
#define FT_BOOL_DEF_ISO_IN              false
#define FT_BOOL_DEF_ISO_OUT             false
#define FT_BOOL_DEF_PULL_DOWN_ENABLE    false
#define FT_BOOL_DEF_SERNO_ENABLE        true
#define FT_BOOL_DEF_USB_VERSION_ENABLE  false
#define FT_INT_DEF_USB_VERSION          0
#define FT_INT_DEF_USB2_VERSION         0x0200

#endif
